# Calamares partitioning configuration
# Defaults to Windows-safe "alongside" option

allowManualPartitioning: true

# Initial selection on the Choice page
# Options: erase, replace, alongside, manual, none
initialPartitioningChoice: alongside

# Filesystem defaults

defaultFileSystemType: "btrfs"
availableFileSystemTypes: [ "btrfs", "ext4" ]

# EFI System Partition mount point
efiSystemPartition: "/boot/efi"

# Swap choices shown to the user
# Options: none, small, suspend, file
userSwapChoices: [ "none", "small", "suspend", "file" ]
initialSwapChoice: "small"