# Calamares settings
# Minimal, Win11Craft focused flow

branding: win11
prompt-install: false

modules:
  - welcome
  - locale
  - keyboard
  - partition
  - summary
  - finished

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - summary
    - finished
  - exec:
    - partition
    - mount
    - unpackfs
    - displaymanager
    - bootloader
    - packages
    - shellprocess@postinstall
